import { mmsCommercialDatabaseClient, mmsCommercialDatabaseClientAvailable, type MmsCommercialDatabaseClient } from "@/lib/mmsCommercialDatabaseClient";
import { normalisePartnerId } from "@/lib/salesPartnerPolicy";

export type PartnerIdAllocation = {
  status: "issued";
  partnerId: string;
  allocationReference: string;
  backend: "zoho-autonumber" | "postgres-sequence";
};

export type PartnerIdAllocationUnavailable = {
  status: "unavailable";
  reason: string;
};

export type PartnerIdAllocationResult = PartnerIdAllocation | PartnerIdAllocationUnavailable;

export type PartnerIdAllocator = {
  issue(applicantRecordId: string, stage?: "Approved" | "Agreement Pending" | "Training"): Promise<PartnerIdAllocationResult>;
};

export const PARTNER_ID_ALLOCATION_REQUIREMENTS = [
  "The allocator must issue MMSP-1001+ identifiers atomically.",
  "The allocator must guarantee one permanent Partner ID per applicant record.",
  "Retries must return the already-issued Partner ID rather than consume a second ID.",
  "The backing Partner ID field must be unique and generated by the backing store, not by max-plus-one application logic.",
  "Every allocation must retain a durable reference to the applicant and the backing allocation record.",
] as const;

export const PARTNER_ID_ALLOCATOR_UNAVAILABLE_REASON =
  "Atomic permanent Partner ID allocation is not configured. Provision the dedicated MMS commercial PostgreSQL registry/sequence before issuing Partner IDs.";

function validApplicantRecordId(value: string): string {
  const id = value.trim();
  if (!/^\d+$/.test(id)) throw new Error("Invalid applicant CRM record ID.");
  return id;
}

export function validateIssuedPartnerId(value: unknown): string {
  const partnerId = normalisePartnerId(typeof value === "string" ? value : "");
  if (!partnerId) throw new Error("Partner ID allocator returned an invalid permanent MMS Partner ID.");
  return partnerId;
}

export function postgresPartnerIdAllocator(client: MmsCommercialDatabaseClient): PartnerIdAllocator {
  return {
    async issue(applicantRecordId: string, stage = "Approved"): Promise<PartnerIdAllocationResult> {
      const crmRecordId = validApplicantRecordId(applicantRecordId);
      const result = await client.query<{ partner_uuid: string; partner_code: string }>(
        "select partner_uuid::text, partner_code from mms_commercial.issue_partner_code_for_crm_record($1, $2)",
        [crmRecordId, stage],
      );
      const row = result.rows[0];
      if (!row) return { status: "unavailable", reason: PARTNER_ID_ALLOCATOR_UNAVAILABLE_REASON };
      const partnerId = validateIssuedPartnerId(row.partner_code);
      return {
        status: "issued",
        partnerId,
        allocationReference: `postgres:${row.partner_uuid}`,
        backend: "postgres-sequence",
      };
    },
  };
}

/**
 * Only report available when the real dedicated MMS PostgreSQL client is wired.
 * A database URL or migration file alone is not enough.
 */
export function partnerIdAllocatorAvailable(): boolean {
  return mmsCommercialDatabaseClientAvailable();
}

export function partnerIdAllocator(): PartnerIdAllocator {
  if (!mmsCommercialDatabaseClientAvailable()) {
    return {
      async issue(applicantRecordId: string) {
        validApplicantRecordId(applicantRecordId);
        return { status: "unavailable", reason: PARTNER_ID_ALLOCATOR_UNAVAILABLE_REASON };
      },
    };
  }
  return postgresPartnerIdAllocator(mmsCommercialDatabaseClient());
}
