import { normalisePartnerId } from "@/lib/salesPartnerPolicy";

export type PartnerIdAllocation = {
  status: "issued";
  partnerId: string;
  allocationReference: string;
  backend: "zoho-autonumber";
};

export type PartnerIdAllocationUnavailable = {
  status: "unavailable";
  reason: string;
};

export type PartnerIdAllocationResult = PartnerIdAllocation | PartnerIdAllocationUnavailable;

export type PartnerIdAllocator = {
  issue(applicantRecordId: string): Promise<PartnerIdAllocationResult>;
};

export const PARTNER_ID_ALLOCATION_REQUIREMENTS = [
  "The allocator must issue MMSP-1001+ identifiers atomically.",
  "The allocator must guarantee one permanent Partner ID per applicant record.",
  "Retries must return the already-issued Partner ID rather than consume a second ID.",
  "The backing Partner ID field must be unique and generated by the backing store, not by max-plus-one application logic.",
  "Every allocation must retain a durable reference to the applicant and the backing allocation record.",
] as const;

export const PARTNER_ID_ALLOCATOR_UNAVAILABLE_REASON =
  "Atomic permanent Partner ID allocation is not configured. Provision a backing registry with an auto-number/sequence plus a unique applicant key before issuing Partner IDs.";

function validApplicantRecordId(value: string): string {
  const id = value.trim();
  if (!/^\d+$/.test(id)) throw new Error("Invalid applicant CRM record ID.");
  return id;
}

export function validateIssuedPartnerId(value: unknown): string {
  const partnerId = normalisePartnerId(typeof value === "string" ? value : "");
  if (!partnerId) throw new Error("Partner ID allocator returned an invalid permanent MMS Partner ID.");
  return partnerId;
}

/**
 * Deliberately false until a transactional backing registry is actually implemented.
 * This prevents admin/UI code from presenting Partner ID issuance as operational merely
 * because an environment variable was set.
 */
export function partnerIdAllocatorAvailable(): boolean {
  return false;
}

/**
 * Current Zoho CRM edition does not support creating the custom Partner Registry
 * module needed for a server-side auto-number sequence. Deliberately fail closed
 * until an atomic backing store is configured. Do not replace this with a
 * "highest existing MMSP number + 1" implementation: concurrent approvals can
 * issue duplicate Partner IDs.
 */
export function partnerIdAllocator(): PartnerIdAllocator {
  return {
    async issue(applicantRecordId: string): Promise<PartnerIdAllocationResult> {
      validApplicantRecordId(applicantRecordId);
      return {
        status: "unavailable",
        reason: PARTNER_ID_ALLOCATOR_UNAVAILABLE_REASON,
      };
    },
  };
}
