export const routes = {
  home: "/",
  aboutMms: "/about-mms",
  whyMms: "/why-mms",
  ourPhilosophy: "/our-philosophy",
  healthJourney: "/health-journey",
  healthDiscovery: "/health-discovery",
  healthScreening: "/health-screening",
  preventiveCare: "/preventive-care",
  longevityMedicine: "/longevity-medicine",
  weightManagement: "/weight-management",
  ivTherapy: "/iv-therapy",
  memberships: "/memberships",
  membership: "/membership",
  treatments: "/treatments",
  healthConcerns: "/health-concerns",
  howItWorks: "/how-it-works",
  education: "/education",
  knowledgeHub: "/knowledge-hub",
  healthArticles: "/health-articles",
  ling: "/ling",
  healthIntelligence: "/health-intelligence",
  internationalMedicineAccess: "/international-medicine-access",
  medicineIntelligence: "/medicine-intelligence",
  insights: "/insights",
  mediaRoom: "/media-room",
  malaysiaThailandCare: "/malaysia-thailand-care",
  onlineDoctor: "/online-doctor",
  clinics: "/clinics",
  scfLabRoadmap: "/scf-lab-roadmap",
  corporateExecutiveWellness: "/corporate-executive-wellness",
  corporateWellness: "/corporate-wellness",
  professionalAllianceProgramme: "/professional-alliance-programme",
  medicalTourism: "/medical-tourism",
  faq: "/faq",
  contact: "/contact",
  bookAppointment: "/book-appointment",
  privacyDisclaimer: "/privacy-disclaimer",
  privacyPdpa: "/privacy-pdpa",
  privacyPolicy: "/privacy-policy",
  terms: "/terms",
  termsOfUse: "/terms-of-use",
} as const;

export const navigation = [
  { label: "Home", href: routes.home },
  { label: "Your Health", href: routes.healthScreening },
  { label: "Care & Treatments", href: routes.treatments },
  { label: "Health Intelligence", href: routes.healthIntelligence },
  { label: "Memberships", href: routes.memberships },
  { label: "Medical Team", href: `${routes.aboutMms}#medical-team` },
  { label: "Locations", href: routes.clinics },
  { label: "International Patients", href: routes.malaysiaThailandCare },
  { label: "Insights", href: routes.insights },
] as const;

export const moreNavigation = [
  { label: "Home", href: routes.home },
  { label: "International Patients", href: routes.malaysiaThailandCare },
  { label: "Insights", href: routes.insights },
  { label: "About MMS", href: routes.aboutMms },
  { label: "Ling", href: routes.ling },
] as const;

export const legalNavigation = [
  { label: "Privacy Policy", href: routes.privacyPolicy },
  { label: "Privacy / PDPA", href: routes.privacyPdpa },
  { label: "Terms of Use", href: routes.termsOfUse },
  { label: "Disclaimer", href: routes.privacyDisclaimer },
] as const;

export const publicSitemapRoutes = [
  routes.home,
  routes.aboutMms,
  routes.whyMms,
  routes.ourPhilosophy,
  routes.healthJourney,
  routes.healthDiscovery,
  routes.healthScreening,
  routes.treatments,
  routes.preventiveCare,
  routes.longevityMedicine,
  routes.weightManagement,
  routes.ivTherapy,
  routes.memberships,
  routes.membership,
  routes.howItWorks,
  routes.education,
  routes.knowledgeHub,
  routes.healthArticles,
  routes.healthIntelligence,
  routes.insights,
  routes.ling,
  routes.clinics,
  routes.internationalMedicineAccess,
  routes.scfLabRoadmap,
  routes.corporateExecutiveWellness,
  routes.corporateWellness,
  routes.professionalAllianceProgramme,
  routes.medicalTourism,
  routes.malaysiaThailandCare,
  routes.faq,
  routes.contact,
  routes.bookAppointment,
  routes.privacyDisclaimer,
  routes.privacyPdpa,
  routes.privacyPolicy,
  routes.terms,
  routes.termsOfUse,
] as const;
