export const routes = {
  home: "",
  aboutMms: "/about-mms",
  whyMms: "/why-mms",
  ourPhilosophy: "/our-philosophy",
  healthJourney: "/health-journey",
  healthDiscovery: "/health-discovery",
  healthScreening: "/health-screening",
  preventiveCare: "/preventive-care",
  longevityMedicine: "/longevity-medicine",
  weightManagement: "/weight-management",
  ivTherapy: "/iv-therapy",
  memberships: "/memberships",
  treatments: "/treatments",
  healthConcerns: "/health-concerns",
  howItWorks: "/how-it-works",
  education: "/education",
  knowledgeHub: "/knowledge-hub",
  healthArticles: "/health-articles",
  ling: "/ling",
  healthIntelligence: "/health-intelligence",
  internationalMedicineAccess: "/international-medicine-access",
  medicineIntelligence: "/medicine-intelligence",
  insights: "/insights",
  mediaRoom: "/media-room",
  malaysiaThailandCare: "/malaysia-thailand-care",
  onlineDoctor: "/online-doctor",
  clinics: "/clinics",
  scfLabRoadmap: "/scf-lab-roadmap",
  corporateExecutiveWellness: "/corporate-executive-wellness",
  corporateWellness: "/corporate-wellness",
  professionalAllianceProgramme: "/professional-alliance-programme",
  medicalTourism: "/medical-tourism",
  faq: "/faq",
  contact: "/contact",
  privacyPdpa: "/privacy-pdpa",
  termsOfUse: "/terms-of-use",
} as const;

export const primaryNavigation = [
  { label: "Your Health", href: routes.healthScreening },
  { label: "Care & Treatments", href: routes.treatments },
  { label: "Health Intelligence", href: routes.healthIntelligence },
  { label: "Memberships", href: routes.memberships },
  { label: "How It Works", href: routes.howItWorks },
  { label: "Locations", href: routes.clinics },
] as const;

export const mobileNavigation = [
  { label: "How MMS Works", href: routes.howItWorks },
  { label: "Memberships", href: routes.memberships },
  { label: "Treatments & Wellness Guide", href: routes.treatments },
  { label: "Health Concerns & Research", href: routes.healthConcerns },
  { label: "Medicine Price Compare", href: routes.medicineIntelligence },
  { label: "Health Intelligence", href: routes.healthIntelligence },
  { label: "Malaysia–Thailand Care Travel", href: routes.medicalTourism },
  { label: "Online Doctor", href: routes.onlineDoctor },
  { label: "Our Clinics", href: routes.clinics },
  { label: "SCF & Future Medicine", href: routes.scfLabRoadmap },
  { label: "MMS Insights", href: routes.insights },
  { label: "Video & Media Room", href: routes.mediaRoom },
  { label: "Regional Care Access", href: routes.malaysiaThailandCare },
  { label: "About MMS", href: routes.aboutMms },
] as const;

export const footerNavigation = [
  { label: "About MMS", href: routes.aboutMms },
  { label: "Memberships", href: routes.memberships },
  { label: "How It Works", href: routes.howItWorks },
  { label: "Health Discovery", href: routes.healthDiscovery },
  { label: "Malaysia–Thailand Care", href: routes.malaysiaThailandCare },
  { label: "Care Travel", href: routes.medicalTourism },
  { label: "Online Doctor", href: routes.onlineDoctor },
  { label: "Our Clinics", href: routes.clinics },
  { label: "MMS Insights", href: routes.insights },
  { label: "Video & Media Room", href: routes.mediaRoom },
  { label: "Education", href: routes.education },
  { label: "Contact", href: routes.contact },
] as const;

export const platformNavigation = [
  { label: "SCF Lab Roadmap", href: routes.scfLabRoadmap },
  { label: "Medicine Access Intelligence", href: routes.internationalMedicineAccess },
  { label: "Ling", href: routes.ling },
] as const;

export const legalNavigation = [
  { label: "Privacy / PDPA", href: routes.privacyPdpa },
  { label: "Terms of Use", href: routes.termsOfUse },
] as const;

export const languages = [
  { label: "EN", href: "/", aria: "English" },
  { label: "BM", href: "/ms", aria: "Bahasa Malaysia" },
  { label: "中文", href: "/zh", aria: "Simplified Chinese" },
  { label: "ไทย", href: "/th", aria: "Thai" },
] as const;

export const publicSitemapRoutes = [
  routes.home,
  routes.aboutMms,
  routes.whyMms,
  routes.ourPhilosophy,
  routes.healthJourney,
  routes.healthDiscovery,
  routes.healthScreening,
  routes.preventiveCare,
  routes.longevityMedicine,
  routes.weightManagement,
  routes.ivTherapy,
  routes.memberships,
  routes.treatments,
  routes.healthConcerns,
  routes.howItWorks,
  routes.education,
  routes.knowledgeHub,
  routes.healthArticles,
  routes.ling,
  routes.healthIntelligence,
  routes.internationalMedicineAccess,
  routes.medicineIntelligence,
  routes.insights,
  routes.mediaRoom,
  routes.malaysiaThailandCare,
  routes.onlineDoctor,
  routes.clinics,
  routes.scfLabRoadmap,
  routes.corporateExecutiveWellness,
  routes.corporateWellness,
  routes.professionalAllianceProgramme,
  routes.medicalTourism,
  routes.faq,
  routes.contact,
  routes.privacyPdpa,
  routes.termsOfUse,
] as const;
