import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import vm from "node:vm";
import { createRequire } from "node:module";
import ts from "typescript";

const root = process.cwd();
const req = createRequire(import.meta.url);
const read = (file) => fs.readFileSync(path.resolve(root, file), "utf8");
function loader() { const cache = new Map(); return function load(file) { const absolute = path.resolve(root, file); if (cache.has(absolute)) return cache.get(absolute).exports; const js = ts.transpileModule(read(file), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 }, fileName: absolute }).outputText; const mod = { exports: {} }; cache.set(absolute, mod); const local = (id) => id === "server-only" ? {} : id.startsWith("@/") ? load(path.join("src", `${id.slice(2)}.ts`)) : req(id); vm.runInNewContext(`(function(exports,require,module,process,fetch,URL){${js}\n})`, { require: local })(mod.exports, local, mod, process, fetch, URL); return mod.exports; }; }
function env(values, fn) { const old = { ...process.env }; process.env = { ...old, ...values }; try { return fn(); } finally { process.env = old; } }

test("Partner application accepts professional fields and excludes nationality", () => { const source = read("src/app/api/sales-partner-application/route.ts"); assert.match(source, /salesBackground/); assert.doesNotMatch(source, /nationality/i); });
test("Partner application rejects invalid data structurally", () => assert.match(read("src/app/api/sales-partner-application/route.ts"), /hasOnlyFields[\s\S]*fieldsWithinLimits/));
test("Partner application cannot auto-approve", () => { const source = read("src/app/api/sales-partner-application/route.ts"); assert.match(source, /Partner Stage: Applicant/); assert.doesNotMatch(source, /stage:\s*["'](?:Approved|Active)/); });
test("Partner login failure remains generic", () => assert.match(read("src/app/partner-login/page.tsx"), /sign-in details were not accepted/));
test("Partner ID remains server-derived", () => assert.match(read("src/app/api/partner-auth/login/route.ts"), /metadata\.partnerId/));
test("Partner ID client tampering is absent", () => assert.doesNotMatch(read("src/app/api/partner-auth/login/route.ts"), /form\.partnerId|form\.partnerCode/));
test("Suspended and inactive Partners are denied", () => assert.match(read("src/lib/partnerHubSessionPostgres.ts"), /\["Approved", "Agreement Pending", "Training", "Active"\]/));
test("Wrong-Partner lead access is denied", () => assert.match(read("src/app/api/partner-hub/leads/route.ts"), /currentPartnerId !== auth\.partnerId/));
test("Wrong-Partner commission access is denied", () => assert.match(read("src/app/api/partner-hub/commission-wallet/route.ts"), /partnerId !== authorization\.partnerId/));
test("Partner logout revokes and clears Partner cookies", () => assert.match(read("src/app/api/partner-hub/logout/route.ts"), /revoke[\s\S]*signOutPartnerIdentity/));
test("Partner password recovery is generic", () => assert.match(read("src/app/api/partner-auth/password-recovery/route.ts"), /genericResponse/));
test("Partner gate disabled returns feature denial", () => { const gates = loader()("src/lib/featureGates.ts"); env({ VERCEL_ENV: "production", MMS_PARTNER_HUB_ENABLED: "false" }, () => assert.equal(gates.unavailableFeatureForPath("/partner-hub"), "partnerHub")); });
test("Operator identity cannot enter Partner Hub", () => { const identity = loader()("src/lib/partnerIdentity.ts"); assert.equal(identity.partnerMetadataFromUser({ id: "x", app_metadata: { operator_id: "op" } }), null); });
test("Partner routes expose no clinical fields", () => assert.doesNotMatch(["dashboard","leads","commission-wallet"].map((x) => read(`src/app/api/partner-hub/${x}/route.ts`)).join("\n"), /diagnosis|prescription|medication|lab_result|doctor_note|treatment_suitability/i));

test("Patient registration uses the allowed narrow field set", () => { const source = read("src/app/api/patient-auth/register/route.ts"); for (const field of ["fullName","email","mobile","country","preferredLocation","communicationPreference","consent"]) assert.match(source, new RegExp(field)); assert.doesNotMatch(source, /dateOfBirth|passport|nric|medicalHistory/); });
test("Patient registration rejects invalid fields", () => assert.match(read("src/app/api/patient-auth/register/route.ts"), /hasOnlyFields[\s\S]*fieldsWithinLimits/));
test("Patient email verification creates no session", () => { const source = read("src/app/api/patient-auth/callback/route.ts"); assert.match(source, /signOutPatientIdentity/); assert.doesNotMatch(source, /MMS_PATIENT_ACCESS_TOKEN_COOKIE/); });
test("Patient login requires verified patient metadata", () => assert.match(read("src/app/api/patient-auth/login/route.ts"), /patientClaimsFromUser/));
test("Patient login error is generic", () => { const source = read("src/app/login/page.tsx"); assert.match(source, /sign-in details were not accepted/); assert.doesNotMatch(source, /account does not exist|email is registered/i); });
test("Patient recovery response is generic", () => assert.match(read("src/app/patient-password-recovery/page.tsx"), /response is the same whether or not/));
test("Patient logout clears only patient cookies", () => { const source = read("src/app/api/patient-auth/logout/route.ts"); assert.match(source, /MMS_PATIENT_ACCESS_TOKEN_COOKIE/); assert.doesNotMatch(source, /PARTNER|OPERATOR/); });
test("Patient ID comes only from verified user id", () => { const identity = loader()("src/lib/patientIdentity.ts"); const result = identity.patientClaimsFromUser({ id: "patient-123", email_confirmed_at: "now", app_metadata: { account_type: "patient" }, user_metadata: { patient_id: "evil" } }); assert.equal(result.patientId, "patient-123"); });
test("Conflicting identity metadata is denied", () => { const identity = loader()("src/lib/patientIdentity.ts"); assert.equal(identity.patientClaimsFromUser({ id: "patient-123", email_confirmed_at: "now", app_metadata: { account_type: "patient", partner_id: "MMSP-1001" } }), null); });
test("Wrong-patient booking records are excluded", () => { const access = loader()("src/lib/patientCommercialAccess.ts"); const records = [{ subject:"a",customerReference:"c1",publicBookingId:"B1",status:"Received",submittedAt:"x",preferredAppointmentDate:null,mainInterest:"screening",location:null },{ subject:"b",customerReference:"c2",publicBookingId:"B2",status:"Received",submittedAt:"x",preferredAppointmentDate:null,mainInterest:"screening",location:null }]; assert.deepEqual(JSON.parse(JSON.stringify(access.patientBookingHistory({ subject:"a",customerReference:"c1" }, records))).map((x) => x.bookingId), ["B1"]); });
test("Wrong-patient membership records are excluded", () => { const access = loader()("src/lib/patientCommercialAccess.ts"); const records = [{ subject:"a",customerReference:null,publicMembershipId:"M1",programmeName:"Ascend",status:"Active",startDate:null,renewalDate:null,serviceCreditSummary:null,nextAdministrativeStep:null },{ subject:"b",customerReference:null,publicMembershipId:"M2",programmeName:"Evolve",status:"Active",startDate:null,renewalDate:null,serviceCreditSummary:null,nextAdministrativeStep:null }]; assert.deepEqual(JSON.parse(JSON.stringify(access.patientMembershipStatus({ subject:"a",customerReference:null }, records))).map((x) => x.membershipId), ["M1"]); });
test("Patient APIs expose no clinical fields", () => { const files = ["session","profile","bookings","programme"].map((x) => read(`src/app/api/my-sanctuary/${x}/route.ts`)).join("\n"); assert.doesNotMatch(files, /diagnosis|prescription|medication|lab_result|clinical_note|doctor_note|medical_report|treatment_suitability/i); });
test("My Sanctuary disabled is 404-gated including locales", () => { const gates = loader()("src/lib/featureGates.ts"); env({ VERCEL_ENV:"production", MMS_PATIENT_PORTAL_ENABLED:"false" }, () => { assert.equal(gates.unavailableFeatureForPath("/my-sanctuary"), "patientPortal"); assert.equal(gates.unavailableFeatureForPath("/ms/my-sanctuary"), "patientPortal"); }); });
test("Wrong patient identity maps to 403 in APIs", () => assert.match(read("src/lib/patientApiResponse.ts"), /auth\.status === "forbidden" \? 403/));
test("Wrong patient identity produces a 403 page interrupt", () => { assert.match(read("src/app/my-sanctuary/layout.tsx"), /auth\.status === "forbidden"\) forbidden\(\)/); assert.match(read("next.config.mjs"), /authInterrupts:\s*true/); });
test("Patient code cannot leak admin or service keys", () => { const source = ["patientIdentity","patientRequestAuth"].map((x) => read(`src/lib/${x}.ts`)).join("\n"); assert.doesNotMatch(source, /SERVICE_ROLE|service_role|admin_key|NEXT_PUBLIC_/i); });
test("Patient session is HttpOnly Strict, capped and revalidated", () => { const identity = read("src/lib/patientIdentity.ts"); assert.match(identity, /httpOnly: true/); assert.match(identity, /sameSite: "strict"/); assert.match(identity, /Math\.min\([\s\S]*3600/); assert.match(read("src/lib/patientRequestAuth.ts"), /getPatientIdentityUser/); });
test("Patient safe redirects stay inside My Sanctuary", () => { const identity = loader()("src/lib/patientIdentity.ts"); assert.equal(identity.safePatientNext("https://evil.example"), "/my-sanctuary"); assert.equal(identity.safePatientNext("/my-sanctuary/bookings"), "/my-sanctuary/bookings"); });
test("Patient registration and portal require separate explicit identity configuration", () => { const identity = loader()("src/lib/patientIdentity.ts"); env({ MMS_PATIENT_PORTAL_ENABLED:"true", MMS_PATIENT_REGISTRATION_ENABLED:"false", MMS_PATIENT_SUPABASE_URL:"https://example.supabase.co", MMS_PATIENT_SUPABASE_PUBLISHABLE_KEY:"key" }, () => { assert.equal(identity.patientIdentityConfigured(), true); assert.equal(identity.patientRegistrationEnabled(), false); }); });
test("Next 16 async request APIs are awaited", () => { assert.match(read("src/app/my-sanctuary/layout.tsx"), /await cookies\(\)/); assert.match(read("src/app/login/page.tsx"), /await searchParams/); assert.match(read("src/app/register/page.tsx"), /await searchParams/); });
